### ISSUE TITLE
Update wgpu-native version

### ISSUE THREAD

**Issue by Trivaxy** [Trivaxy/WGPU.NET#6]
We need to update our bindings and wrappers to target to v0.14.2.2.
I've updated the bindings generator and moved the new bindings to the WGPU.NET project, but the tests (and appropriate wrapper changes) need changing as they don't work anymore.

@jupahe64 Would you mind looking into the test and API you wrote and updating them?

**Comment by jupahe64** [comment]
I got it working but only for Vulkan, DX12 has some memory issue that I can't really figure out and DX11 has no adatper apparently
oh and OpenGL seems to be hidden behind a build flag
anyway I'll still commit it cause it's definitly better than nothing
